### PR TITLE
Test for opening external links in new tabs

### PR DESCRIPTION
**Pull request by SteveKola**
**References Issues:**

#533 

Signed-off-by: Steven Kolawole <45284829+SteveKola@users.noreply.github.com>

### CODE REVIEW

**Comment by SteveKola** [comment]
@klumb, do tell me once you've tested it on the website.
I have my fingers crossed here 😄

**Comment by klumb** [comment]
you can check it here

https://chaoss.community/metrics-prototype-1/

**Comment by SteveKola** [comment]
Oops! Not working. 😞 

So I checked the solution link again and apparently, we need to add `markdown: kramdown` to the file `_config.yml`. I guess that's where the error is coming from.

Could we try that out? I guess we could always revert if it doesn't work out fine.

https://stackoverflow.com/a/63546509

**Comment by klumb** [comment]
@SteveKola go ahead

**Comment by SteveKola** [comment]
> @SteveKola go ahead

@klumb, I'm on it. 
I checked but there's no preexisting `_config.yml` in the repo, so that means I'd have to create one.

I'm lost on which directory to create it in though. Can I create `_config.yml` in the base folder?

**Comment by klumb** [comment]
@SteveKola - oh sorry, I didn't read what the solution is.

I don't think we will be able to use this solution.

**Comment by SteveKola** [comment]
> @SteveKola - oh sorry, I didn't read what the solution was.
> 
> I don't think we will be able to use this solution.

Oh alright. At least we tried. Thank you for indulging me. 🥰 

Should I revert the changes and push or you'd do it from your end?

**Comment by klumb** [comment]
That's okay, that file isn't being used currently so we can just keep it as a test file.

**Pull request merged**
