### PR TITLE
Update meeting times and google Doc link

### PR DESCRIPTION
**Pull request by vinodkahuja**
Updating meeting times after the consent of regular participants and also updating google Docs link as the old Doc was owned by Andy. A new copy is created and ownership of the new one is transferred to CHAOSS project.

Signed-off-by: Vinod K. Ahuja  <vahuja@unomaha.edu>

### CODE REVIEW

**Comment by GeorgLink** [comment]
While you are editing the schedule, can you please add a AreWeMeetingYet.com link?

```
[check your local time](...)
```

**Comment by vinodkahuja** [comment]
@GeorgLink done.

**Comment by klumb** [comment]
@vinodkahuja please fix DCO

**Comment by vinodkahuja** [comment]
@klumb something is wrong with DCO bot implementation. I have already provided the sign-off but it is still giving the sign-off error. 
**Screenshot below:**

image

**Comment by klumb** [comment]
@vinodkahuja are you sure the issue is with the DCO bot and not on your end?

How are you signing off on these?

**Comment by vinodkahuja** [comment]
I hope so. I am following proper sign off as follows:

Signed-off-by: Vinod K. Ahuja <vahuja@unomaha.edu>

**Comment by klumb** [comment]
Are using Git? or the Github interface?

**Comment by klumb** [comment]
I opened an issue here https://github.com/chaoss/governance/issues/237

I am manually setting your DCO to pass.

**Comment by vinodkahuja** [comment]
@klumb for this pull request I used the GitHub interface. Previously I have also tried with a thrid party software like [Gitkraken](www.gitkraken.com) and was getting the same error.

**Pull request merged**
