### PR TITLE
Optimized Images

### PR DESCRIPTION
**Pull request by vardaan-raj**

### CODE REVIEW

**Comment by GeorgLink** [comment]
Could you please add a description and let us know what the goal of this PR is?

**Comment by klumb** [comment]
Also, please add any relevant information on ImgBot.

**Comment by vardaan-raj** [comment]
> Could you please add a description and let us know what the goal of this PR is?

I basically optimized the images by compressing their size without compromising quality. I used imgbot for the same.

**Comment by vardaan-raj** [comment]
> Also, please add any relevant information on ImgBot and permissions.

mgbot is a friendly robot that optimizes your images and saves you time. Optimized images mean smaller file sizes without sacrificing quality. ... As you work on your project, Imgbot works alongside you to keep your images optimized. Imgbot uses lossless compression by default.

**Comment by klumb** [comment]
Please provide some further information on why we need this PR, what it fixes, what 
imgbot is, and your association with it.

**Comment by vardaan-raj** [comment]
I have basically compressed your image sizes so they occupy much less space
than before, I have used IMGBOT which Is basically an application that is
used for compressing images without compromising their quality.

**Comment by klumb** [comment]
@vardaan-raj, thank you for the PR.
 
We can all agree that optimized images are a good thing, but this PR isn't a response to an observed issue. These are questions I have, that haven't been answered:

- Was a problem observed with the images before? 
- If no problem was observed, what is your motivation for this PR? Is there a justification for why we should use this tool to modify all of our images?
- What are the security issues? I am not familiar with Imgbot. I don't know what the bot is doing to the images. Is it just compressing them, or is it inserting code as well? What are our assurances about this?
- What is your affiliation with ImgBot? Do you have permission to use it for this? Do we have permission? If it is free to use, is there a process we need to go through?

Because this is an unsolicited PR and it affects many files these concerns need to be addressed.

**Pull request closed without merging**
