### PR TITLE
Add remaining descriptions to Beginners.MD

### PR DESCRIPTION
**Pull request by AayushTyagi1**
This commit adds remaining page descriptions to the table present under Beginners.MD

### CODE REVIEW

**Comment by klumb** [comment]
Thanks @AayushTyagi1 

Could you fix the DCO on this so that I can merge it?

here is a link to the contributors guide (includes DCO)
https://github.com/chaoss/governance/blob/f6d6d3480bad92bb197ad0e3132d7e4a91fd8a58/CONTRIBUTING.md

**Review by AayushTyagi1 — COMMENTED** [review]
Working on it.

**Comment by klumb** [comment]
if you need to manually sign off, you can just add this text to a comment:

Signed-off-by: Your Name <YourName@example.org>

**Review by AayushTyagi1 — COMMENTED** [review]
Signed-off-by: Aayush Tyagi <tyagiaayush5@gmail.com>

**Comment by seun-beta** [comment]
@klumb I can see that @AayushTyagi1 has added some more structure to the beginners guide. Do you think there is need to  some more explanation into the documentation?

**Comment by klumb** [comment]
@seun-beta
 yes, I consider this document to be a work in progress. It needs more attention.

**Pull request merged**
