### PR TITLE
created the a folder and added the gdpr.md file that contain the ethical use of grimoirelab

### PR DESCRIPTION
**Pull request by Enecode**

### CODE REVIEW

**Comment by germonprez** [comment]
Thanks for this @Enecode -- Right now, we do have a data ethics statement at the end of every metric. You can see an example here: https://chaoss.community/kb/metric-test-coverage/

Does your PR potentially align with this?

**Comment by Enecode** [comment]
> Thanks for this @Enecode -- Right now, we do have a data ethics statement at the end of every metric. You can see an example here: https://chaoss.community/kb/metric-test-coverage/
> 
> Does your PR potentially align with this?

I can't say for sure.

**Comment by germonprez** [comment]
My inclination is to have a single GDPR-related statement in the project -- and right now this is at the end of the metrics. 

I'm curious what @ElizabethN thinks.

**Comment by ElizabethN** [comment]
@Enecode Hi! :wave: So @peculiaruc and I talked about this, and what might be better is to link to our standard docs: 

 - [Data Ethics Statement](https://github.com/chaoss/community/blob/main/data-ethics-statement.md)
 - [Data Use Awareness Statement](https://github.com/chaoss/community/blob/main/data-use-statement.md)
 
 That way we are all pulling from the same place and there is one source of truth. 

Gonna close this PR for now. Thank you so much for your work here @enecodes!

**Comment by Enecode** [comment]
That's great. Thanks @ElizabethN

**Pull request closed without merging**
