### PR TITLE
updated info about the Value WG

### PR DESCRIPTION
**Pull request by vchrombie**
Updated the information about the Value WG. https://github.com/chaoss/wg-value/issues/9

- [ ] _Home_: Add a bullet item for "Value"
- [x] _About_: Add a bullet item for "Value Metrics WG"
- [x] _Metrics Page_: Use the existing content as a template for a "Value Metrics" block
- [x] _Participate Page_: Use the Common Metrics content as a template for a "Value Metrics" block

I couldn't find the _Home Page_ to add a bullet item for "Value". I thought this would be the file, https://github.com/chaoss/website/blob/master/Home/about-us.md but I cannot see any items.

Is the _Home Page_ managed by Wordpress or am I mistaken?

Can anyone help me with this?

If you need any changes, I am ready to make them. :slightly_smiling_face:

### CODE REVIEW

**Comment by vchrombie** [comment]
Oh, I just noticed one thing.

@germonprez has sent one PR https://github.com/chaoss/website/pull/137. My PR https://github.com/chaoss/website/pull/143 has the same change which may result in a merge conflict. :sweat_smile: 

Sorry for that. I didn't see it. May be you can merge his first and I will update my PR with the changes. Anyway this PR needs some discussion I guess. :slightly_smiling_face:

**Comment by vchrombie** [comment]
@klumb, thanks for the changes. :slightly_smiling_face:

**Comment by klumb** [comment]
@vchrombie , thanks I fixed it.

**Comment by klumb** [comment]
@vchrombie,  Regarding the bullet point on home page, we haven't created the mark down file for that module yet. It is currently just in a word press text box.

**Comment by vchrombie** [comment]
@klumb, thanks for the changes. But I didn't complete one more thing. I have a doubt regarding that.

**Comment by vchrombie** [comment]
> @vchrombie, Regarding the bullet point on home page, we haven't created the mark down file for that module yet. It is currently just in a word press text box.

Ok, thanks for the reply. 

Can you add "Value" in that word press text box?

**Comment by klumb** [comment]
@vchrombie, yes It is changed now.

 Next time we need to modify that module, we will replace it with a markdown file.  Thank you!

**Comment by vchrombie** [comment]
Thank you so much @klumb.

> Next time we need to modify that module, we will replace it with a markdown file. Thank you!

Ya sure. :smiley:

**Pull request merged**
