### PR TITLE
Add more ways of participating

### PR DESCRIPTION
**Pull request by xiaoya-Esther**
Signed-off-by: Xiaoya <xiaoyaxiaesther@gmail.com>

I add the Slack inviting link.

The Tencent meeting link was discussed at the last Asia-Pacific call. This meeting is meant to let Chinese speakers feel less stressed to join the community.

### CODE REVIEW

**Comment by klumb** [comment]
Thanks @xiaoya-Esther 

Can you add the day of the week for the tencent meeting?

Also, I was going to add the BJT timezone to all of our meetings. Would it be better to use BJT or GMT+8?

**Comment by xiaoya-Esther** [comment]
Hi @klumb !
> Can you add the day of the week for the tencent meeting?

Done.


> Also, I was going to add the BJT timezone to all of our meetings. Would it be better to use BJT or GMT+8?

Thanks for this! I think GMT+8 sounds good.

**Comment by germonprez** [comment]
Hi @klumb could you check this out an merge if all good?

**Comment by klumb** [comment]
The only concern I have is that the tencent meeting doesn't match our normal convention for meetings/working groups. Our norm is make a module for the group or add it to the calendar. 

I was contemplating accepting the PR and sorting it out after the migration.

**Pull request merged**
