### PR TITLE
Add Helpful Links to D&I Page

### PR DESCRIPTION
**Pull request by Nebrethar**
This work is thanks to @bistaastha who collected the information for me. This adds helpful information to the D&I page on the website. @klumb I may need your help making it look good on the website.

Signed-off-by: Matt Snell <msnell@unomaha.edu>

### CODE REVIEW

**Comment by Nebrethar** [comment]
Thanks @klumb !!

I don't see anything yet, but I will check in about an hour and send an update then

**Comment by Nebrethar** [comment]
2 Days Later... lol. @klumb 

I am still not seeing anything on the website 🤔 Maybe it still has to manually be updated?

**Comment by klumb** [comment]
Sorry that was my bad. Forgot that app master had to be manually pulled to the website. 

It should be there now but it looks like it has issues.

**Comment by Nebrethar** [comment]
It's wild, how many issues pop up when you put it in production ;)

#499 should fix it...

**Pull request merged**
