### PR TITLE
Rpaik patch 1

### PR DESCRIPTION
**Pull request by rpaik**
Created a folder for CHAOSScon-EU 2020 slides

### CODE REVIEW

**Comment by GeorgLink** [comment]
Thanks @rpaik 
I agree with Dawn about removing special characters like spaces or ampersands.

**Comment by rpaik** [comment]
Thanks Dawn and Georg. Uploaded renamed files (it doesn't look like there's a way to rename an uploaded file?)

**Comment by GeorgLink** [comment]
I don't think the GitHub UI has that feature. I would work locally for those kind of changes.

**Comment by GeorgLink** [comment]
It also looks like the DCO check is failing

**Comment by rpaik** [comment]
I set it to pass :-)

**Comment by klumb** [comment]
LGTM

**Pull request merged**
