### PR TITLE
Switch Lightning Talks and Int. Session 1

### PR DESCRIPTION
**Pull request by ElizabethN**
Signed-off-by: Elizabeth Barron <elizabeth@naramore.net>

### CODE REVIEW

**Comment by ElizabethN** [comment]
@germonprez this is what we talked about in the meeting today, right?

**Comment by germonprez** [comment]
That works! The other option is to combine them in a single session. Something like:

| 8:00 | Check-in and networking and Coffee |
| 8:30 | Welcome |
| 8:45-9:15 | Expert Panel: Greatest Needs for CHAOSS |
| 9:20-9:55 | Interactive Session 1 - CHAOSS and Open Source Program Offices |
| 9:55-10:15 | Coffee and Tea Break |
| 10:15-10:50 | Interactive Session 2 - Future CHAOSS Efforts |
| 10:50-11:40 | Lightning Talks / Report out and group discussion |
| 11:40 | Closing |
| 11:55 | Group photo |
| 12:00-13:30 | LUNCH (attendees on their own) |

**Comment by ElizabethN** [comment]
@germonprez ohhh I gotchoo, I didn't fully understand what you meant but that makes complete sense now. Thanks!

**Comment by ElizabethN** [comment]
@germonprez I'm gonna merge this now, thanks for your :eyes:!

**Comment by germonprez** [comment]
right on

**Pull request merged**
