### PR TITLE
Add speaker headshots for 2022EU

### PR DESCRIPTION
**Pull request by ElizabethN**
@klumb I'm not sure how the sizing of these will look on the page, so if we have to adjust that we can.

Also, we are missing one headshot but I should have that tomorrow. 

Thank you!

### CODE REVIEW

**Comment by klumb** [comment]
Did we ask for a specific size on these? 
Because we are working in markdown, we don't have the ability to resize the shots in the script. 
I will download them and resize them tomorrow.

**Comment by klumb** [comment]
I think we resize these to 300x300. Maybe next time we should add that to the form.

**Comment by klumb** [comment]
Because we are working in markdown, we don't have the ability to resize the shots in the script.

I will download them and resize them tomorrow.

**Comment by klumb** [comment]
Thanks @ElizabethN

**Comment by ElizabethN** [comment]
Ok sounds good. If you are tied up I can do it on Thursday. Thanks @klumb!

**Comment by ElizabethN** [comment]
@klumb I added the final screenshot, FYI.

**Pull request merged**
