### PR TITLE
Schedule change per Daniel's request

### PR DESCRIPTION
**Pull request by klumb**
@ Georg, can you take a look at this and merge it. I did this pretty fast flight. I will forward you the email.

### CODE REVIEW

**Comment by klumb** [comment]
There are some weird commit issues here. Sorry, @georg any chance you could clean it up a bit for me? I was a little hurried and apparently my repository was not up-to-date.

**Comment by GeorgLink** [comment]
sure, I'll have a look

**Comment by GeorgLink** [comment]
I'll do it later today

**Comment by klumb** [comment]
Thanks, I am at the airport now. Flight isn’t cancelled yet. :)




Cheers, 


Kevin Lumbard (he/him/his)
University of Nebraska at Omaha
PKI 367

**Comment by GeorgLink** [comment]
I'll make a new commit outside this pull request because some changes in unrelated files.

**Comment by GeorgLink** [comment]
it's done

**Comment by klumb** [comment]
Thanks!


Cheers, 


Kevin Lumbard (he/him/his)
University of Nebraska at Omaha
PKI 367

**Pull request closed without merging**
