### PR TITLE
Technical Fork

### PR DESCRIPTION
**Pull request by vinodkahuja**
continuous release metric technical fork.

Signed-off-by: Vinod Kumar Ahuja  <vahuja@unomaha.edu>

### CODE REVIEW

**Comment by klumb** [comment]
there are several issues with this PR.

I propose we close it and start over.

@vinodkahuja can I close this and ask you to resubmit?

**Comment by vinodkahuja** [comment]
Sure. Can you please highlight the issues so that I get to know what to fix in the new PR.

**Comment by klumb** [comment]
There is a merge conflict with about/media/coverage.md - not sure why.
There is a DCO error
There are several people and commits included here that don't seem related to the Technical Forks PR
and I don't even see the commit that actually adds technical forks to the continuous release

**Comment by klumb** [comment]
okay i see the technical forks file commit now but the link to the metric page is incorrect

**Comment by vinodkahuja** [comment]
Ok close it and I will create a new PR

**Comment by klumb** [comment]
Thanks

**Pull request closed without merging**
