### PR TITLE
Delete old DEI Badging app

### PR DESCRIPTION
**Pull request by Nebrethar**
Removing the old version of the DEI Badging app (Name changed)

### CODE REVIEW

**Comment by klumb** [comment]
@Nebrethar can you take a look at this?

**Comment by Nebrethar** [comment]
@klumb I can't fix my DCO signoff on this computer. Every time I fix my signoff, my git client will create a new commit that is not signed off.

This is just an attempt to remove an old file. I will create a new PR.

**Comment by klumb** [comment]
I can over-ride the DCO if you want to avoid a new PR

**Comment by Nebrethar** [comment]
Already made it 😛 I'd rather avoid using "set to pass"

**Pull request closed without merging**
