### PR TITLE
Created a PR for my Outreachy article 

### PR DESCRIPTION
**Pull request by thecraftman**
Hello @germonprez  @GeorgLink @klumb  I've attached the markdown format for my article here.

Thanks

### CODE REVIEW

**Comment by germonprez** [comment]
Hi @thecraftman, could you provide a DCO sign-off on this PR? This is something that we require on all PRs.

**Comment by thecraftman** [comment]
> Hi @thecraftman, could you provide a DCO sign-off on this PR? This is something that we require on all PRs.

Done.

**Comment by klumb** [comment]
Thanks @thecraftman!

LGTM

**Comment by klumb** [comment]
We are live on the website:
https://docs.google.com/document/d/1xsii5tfmmDwWpuhrFcBJMeYeT3RipJdiCdHrbi0NalQ/edit#

**Pull request merged**
