### PR TITLE
Delete prospector.md

### PR DESCRIPTION
**Pull request by mpgjon**
per open pull request, removing prospector.md

### CODE REVIEW

**Comment by klumb** [comment]
Thanks @mpgjon,

Please add a DCO sign off to the pull request and I a will merge.

**Comment by mpgjon** [comment]
> Thanks @mpgjon,
> 
> Please add a DCO sign off to the pull request and I a will merge.

I'm a github n00b, so once I figure out how to do that, hopefully today, will happily do so! :)

**Comment by klumb** [comment]
No worries, if you follow the action required link it should give you directions on how to do it. If you are unable to complete that process, add your signoff into a comment and I will force the merge.

**Comment by mpgjon** [comment]
If you get a moment, perhaps this pr is correct: https://github.com/chaoss/website/pull/181/files#diff-d01dcf55230d17e67ec79fde92659520 - I added the signed-off in the code at the head, is that correct?  Thanks so much.

**Comment by klumb** [comment]
Sorry, it can be a little tricky adding it after the PR.
Here check this out.
https://github.com/chaoss/website/pull/181/checks?check_run_id=153346352

You don't want to add it directly to the code.
The link above should tell you how to add it after the PR has been made.

In the future, you just need to add a -s to your git commit
Example: git commit -s -m "this is my message" 

please remove the sign off from the code. If you follow the steps in the link above and are unable to get the signoff, take the text you added to the code and put it into a comment, and I will force the merge.

**Comment by GeorgLink** [comment]
Hi @mpgjon thanks for submitting this pull request.

You have two ways to resolve the DCO issue:
1. fix it in this pull request, as @klumb suggested.
2. create a new pull request with the correct DCO.

For a beginner, I suggestion option 2. Scratch this pull request and use either [a Browser extension](https://github.com/scottrigby/dco-gh-ui) for making changes in the GitHub interface or run `git commit` with the `-s` option on a local machine. 

If you like, I can also jump on a video call and we can talk though this together.

**Pull request closed without merging**
