### PR TITLE
Reduced image size

### PR DESCRIPTION
**Pull request by Anita-ihuman**

### CODE REVIEW

**Comment by ElizabethN** [comment]
I think this image looks good! 👍  from me @Anita-ihuman and @klumb

**Review by germonprez — APPROVED** [review]

**Comment by germonprez** [comment]
@GeorgLink you're waay better at merge conflicts than I am :) Can you help me out here so that we can merge this?

**Comment by klumb** [comment]
@GeorgLink I will take care of this

**Comment by GeorgLink** [comment]
Thanks for the compliment @germonprez 

Thanks for taking care of this @klumb

**Comment by klumb** [comment]
this is pretty broken so I am closing this and putting in a new PR #702

**Pull request closed without merging**
