### PR TITLE
add gsoc-acceptance-venu blog post

### PR DESCRIPTION
**Pull request by vchrombie**
Hi @klumb 

I thought of publishing my gsoc-acceptance blog post on the CHAOSS website. I had this thing in my head for a long time. Finally, I could grab some time for this.

I have added the blog post, content everything as per the instructions. Please let me know if I did anything wrong.

Also, I have published this blog post on my personal blog, https://vchrombie.github.io/blog/gsoc-acceptance. If you feel that the content needs some editing to go onto the CHAOSS website, please feel free to suggest any changes. :smiley:

cc @GeorgLink

### CODE REVIEW

**Comment by klumb** [comment]
This looks good. Thanks @vchrombie. I will publish this on Monday.

**Comment by vchrombie** [comment]
> This looks good. Thanks @vchrombie. I will publish this on Monday.

Thanks, @klumb. :smile:

**Comment by klumb** [comment]
@vchrombie 

How does this look?

https://chaoss.community/mentorship-blog/2020/06/01/google-summer-of-code-intern-venu-vardhan-reddy-tekula/

**Comment by vchrombie** [comment]
> @vchrombie
> 
> How does this look?
> 
> https://chaoss.community/mentorship-blog/2020/06/01/google-summer-of-code-intern-venu-vardhan-reddy-tekula/

Hi @klumb, it looks great. :smiley: 
Thanks for the help.

I have a small suggestion. How about adding the link to [mentorship-blog](https://chaoss.community/category/mentorship-blog/) to the website. I didn't find it anywhere.

Maybe in the [CHAOSS Mentorship](https://chaoss.community/chaoss-mentorship/) page or [blog](https://chaoss.community/blog/) or under the Community section in the nav-bar, wherever you feel it would suit. :smile: 

WDYT?

**Pull request merged**
