### PR TITLE
post about community managers

### PR DESCRIPTION
**Pull request by sgoggins**
Adding a new news post about community managers.

### CODE REVIEW

**Comment by klumb** [comment]
I will have to convert it to plain text anyway because we don't currently have the ability to create WordPress blogs in markdown ( I am trying to get this feature turned on but haven't heard back from Linux IT support).
 
So this is fine, I will let you know when I post it to get a final approval.

**Comment by klumb** [comment]
Sorry accidentally closed. Reopened.

**Comment by klumb** [comment]
Sure

**Comment by GeorgLink** [comment]
Does that html-html transfer reduce the workload compared to
markdown-wordpress?

**Comment by klumb** [comment]
Merging and posting

**Pull request merged**
