### PR TITLE
Rename 202008_release_finalized.md to 20200811_release_finalized.md

### PR DESCRIPTION
**Pull request by ElizabethN**
Signed-off-by: Elizabeth Barron <elizabeth@naramore.net>

### CODE REVIEW

**Comment by ElizabethN** [comment]
@klumb sadly I forgot that dates have days and this wasn't posting to the site properly, so I had to rename the file. My bad! If you can re-merge this, that would be great. 🙏

**Comment by ElizabethN** [comment]
@klumb thank you! Is there a reason this wouldn't automatically be uploaded to the blog? What else did I mess up? 🤦‍♀️

**Comment by klumb** [comment]
Okay, I pulled it the website

**Comment by ElizabethN** [comment]
@klumb you are fantastic! Thank you!!

**Comment by klumb** [comment]
We just have to create the github module and link it to the file. Process isn't fully automated. Requires a manual pull. I can show you how to do this if you would like.

**Comment by ElizabethN** [comment]
@klumb sure! It's nothing urgent, so next time we have a minute we can roll through it. :+1:

**Pull request merged**
