### PR TITLE
New BlogPost: MozFest session recap

### PR DESCRIPTION
**Pull request by GeorgLink**
This blog post is a MozFest session recap with one image.

On 11/12 at 4am CST, https://software.ac.uk will publish the same article. Maybe we can schedule the same release time?

Best,
Georg

### CODE REVIEW

**Comment by GeorgLink** [comment]
https://docs.google.com/document/d/1r1coredAHoE1Spd4S4nXsacyM8nqczruQNzDR8U4KF0/edit

**Comment by klumb** [comment]
@GeorgLink this is now live.

https://chaoss.community/blog-post/2018/11/08/open-community-metrics-and-privacy-mozfest18-recap/

**Comment by GeorgLink** [comment]
Thank you. Can you delay publication until Monday?

**Comment by GeorgLink** [comment]
@klumb The link to the blog post is 404 NOT FOUND. Can you please make the post available?

**Comment by klumb** [comment]
@GeorgLink it is live
please review

**Comment by GeorgLink** [comment]
Thank you!

**Pull request merged**
