### PR TITLE
fix: Made community report's first name mandatory

### PR DESCRIPTION
**Pull request by covalentbond**
Signed-off-by: Arijit Kundu kunduarijit55@gmail.com

1. Fixes: #525 
2. Added * before all the text fields which are mandatory

image

### CODE REVIEW

**Comment by klumb** [comment]
@covalentbond the image fields are not required. Please edit.

**Comment by klumb** [comment]
Also, the asterisk aren't necessary

**Comment by covalentbond** [comment]
@klumb can you please review!

**Comment by klumb** [comment]
Looks good!

**Pull request merged**
