### PR TITLE
added DEI V3 blogbost

### PR DESCRIPTION
**Pull request by Anita-ihuman**
Signed-off-by: Anita-ihuman <charlesanita403@gmail.com>

### CODE REVIEW

**Comment by germonprez** [comment]
This is great! Thanks @Anita-ihuman

**Comment by germonprez** [comment]
I'd merge but I'm not sure if someone else typically merges the blog posts.

**Comment by GeorgLink** [comment]
@klumb usually merges blog posts when adding them to the website.

**Comment by ElizabethN** [comment]
I think I can merge! I will give it a try.

**Pull request merged**
