### PR TITLE
Fix link to Common WG in Working Groups list

### PR DESCRIPTION
**Pull request by jsmanrique**
Fix chaoss/website#231

### CODE REVIEW

**Comment by GeorgLink** [comment]
Thanks @jsmanrique !!!

**Comment by GeorgLink** [comment]
@jsmanrique could you fix your DCO please? If not, I can create a new commit, but you would not get credit for it then 😯

**Comment by jsmanrique** [comment]
> @jsmanrique could you fix your DCO please? If not, I can create a new commit, but you would not get credit for it then 😯

I'm working on it ;-)

**Comment by GeorgLink** [comment]
Thank you

**Comment by jsmanrique** [comment]
I am blocked trying to commit the DCO change:
```
git push --force-with-lease origin patch-1
Username for 'https://github.com': jsmanrique
Password for 'https://jsmanrique@github.com':
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects:  50% (2/4)
```

I have already tried to change `http.postBuffer` to 1GB, but it keeps hanging at 50% 😞

**Comment by GeorgLink** [comment]
hm... maybe create a new branch and submit a new PR? (not a great solution,
but it should work).

**Comment by jsmanrique** [comment]
It seems I am not able to solve this with this branch, so I'll close the PR and try to submit a new one

**Pull request closed without merging**
